### ISSUE TITLE
Long NFO file in lines gets cropped

### ISSUE THREAD

**Issue by roro7302** [mackonsti/yet-another-nfo-viewer#4] opened 2022-05-15 16:22 UTC
Hi
About big nfo, with many lines. Do you have a fix ?
exemple : Alain_Tremblay-Le_Poids_Des_Papillons-WEB-FR-2022-SORCiERE

YaNvi is broken is blocked around line 130.

thx you again for this project.

**Comment by mackonsti** [comment] 2022-05-15 19:58
Salut, I am sorry but I no longer maintain the code as it dates back to Xcode 3...
Are. you referring to the FILENAME being too long and not opening?
What is the issue? The title on the window or the file not opening at all?

> aNvi is broken is blocked around line 130.

Which file in the project please?
Merci !

**Comment by roro7302** [comment] 2022-05-15 20:10
Hi.

in fact, if the nfos you open have a lot of lines in them (example: beautiful drawings inside).
With YaNvi, we only see part of the nfo and it does not display the entire nfo.
in comparison with bbedit, for example, YaNvi shows me only about 130 lines of nfo on the whole.

Two video for exemple

https://i.imgur.com/FOD6z6G.mp4 > YaNvi
https://i.imgur.com/h3p9xD0.mp4 > BBedit (or Textedit or anithing)

sorry, im not developpers, im just a bug reporter ^^'
________________________________
De : MacKonsti ***@***.***>
Envoyé : dimanche 15 mai 2022 21:58
À : mackonsti/yet-another-nfo-viewer ***@***.***>
Cc : roro7302 ***@***.***>; Author ***@***.***>
Objet : Re: [mackonsti/yet-another-nfo-viewer] long nfo (Issue #4)


Salut, I am sorry but I no longer maintain the code as it dates back to Xcode 3...
Are. you referring to the FILENAME being too long and not opening?
What is the issue? The title on the window or the file not opening at all?

YaNvi is broken is blocked around line 130.

Which file in the project please?
Merci !

**Comment by mackonsti** [comment] 2022-05-15 20:33
OK now I understand. Merci.
However in the code, there was no limit to the lines read of the NFO file.
That would be a little stupid to limit it 😄 
So I think it may be due to an older method reading contents and displaying in the window.
So you cannot **scroll** inside the window, is that it?
What is the file size of these drawings, please?
Can you share via workupload.com an example or drag-n-drop it here, inside the text of your reply, to understand the behaviour?
I will need to ask one of the two people that were kind enough to update the compiled code if they have time to check it out.
Thanks

**Comment by roro7302** [comment] 2022-05-16 20:37
I am attaching an nfo with about 300 lines
https://workupload.com/file/XTfu38cwfxS

**Comment by mackonsti** [comment] 2022-05-17 12:29
Salut @roro7302 I see now the issue. I cannot know exactly why it's cropped after some lines, I can reproduce the problem with the latest 1.1.2 release on Catalina.

@skylex do you have perhaps the time and energy to have a look as you are more comfortable with the code than myself? Haven't coded for ages... thanks!

**Comment by leszek-s** [comment] 2022-06-07 19:25
Hi @mackonsti the problem is that in MainMenu.xib file the TextView in NFOViewer->View->ScrollView->ClipView->TextView has a property maximum size which is set to 2000 for both width and height. If I change maximum height there from 2000 to for example 200000 then it works.

**Comment by mackonsti** [comment] 2022-06-07 19:43
Hi @leszek-s thank you for your valuable feedback.
Does the scroll bar appear to make the window user-friendly and scrollable?
I guess we could try this, but 200 000 is a little much don't you think? 😄 
Perhaps set it to 9 000 should be enough for the ASCII art file posted above?
If you are in a position to compile it (hopefully for both Intel and Apple Silicon) you are welcome to do so and I can happily give you collaborator access to post a release.
I am not in a position to compile anything, anymore...
Thank you!

**Comment by leszek-s** [comment] 2022-06-08 18:37
I created a pull request with a fix also on my fork https://github.com/leszek-s/yet-another-nfo-viewer I commited a compiled 1.1.3 version in zip file so you can post it as a release on your repo if you want. I only tested it on intel mac but I think it should work on apple silicon also.

**Comment by mackonsti** [comment] 2022-06-08 19:28
Thank you @leszek-s for your contribution, I have an M1 at work, I will test it tomorrow and provide my feedback.
So eventually how many lines you made it read? 😄

**Comment by skylex** [comment] 2022-06-08 20:42
Sorry I didn't have time to look into it and I'm not very familiar with Xcode anyway.
Thanks @leszek-s it's working on my M1 and I can confirm it's listed as a native Apple Silicon app in process list.
And the fix is working with the NFO file provided.

**Comment by mackonsti** [comment] 2022-06-09 12:37
Thank you both @skylex and @leszek-s for your great help, I will close this ticket and very soon will publish the new version as a new Release! 👍

**Closed** 2022-06-09 22:47 UTC

**Comment by roro7302** [comment] 2022-06-10 18:10
Thank everyone !
